### ISSUE TITLE
New Similarity in similarity_metrics.py

### ISSUE THREAD

**Issue by sohaibumar62** [aiengineer/NUSCCF#5]
Hi...
It seems new similarity for indirect nbr is calculated through **joint direct neighbor** but only target user and indirect nbr is passed through new_sim(TUser, NUser, mlist, list_with_rating) function. How it is calculating sim for indirect nbr???

**Comment by soran-ghaderi** [comment]
hi Sohaib,
thanks for your information, unfortunately, this version is not the final one I proposed but you are right. Right now, I don't have access to my original codes due to some reasons. but another part that is not contained in this version is the clustering part. anyway, this repo is an implementation of the paper referred to in the references. By adjusting some details like the one you just mentioned, you can run it without any problem.

feel free to **fork** this repository and improve it as you like.
